name: Deploy HTML website

on:
  push:
    branches:
      - master  # Change to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages  # Change to your desired branch (usually gh-pages for GitHub Pages)
        FOLDER: test # Change to the folder containing your HTML website files
